In [1]:
# Create a function that cleans everything we need to clean

In [2]:
import pandas as pd
import numpy as np

In [3]:
# get the data
fifa_predict = pd.read_csv('fifa21_validate.csv')

In [4]:
fifa_predict.head()

,ID,Name,Age,Nationality,Club,BP,Position,Team & Contract,Height,Weight,...,CDM,RDM,RWB,LB,LCB,CB,RCB,RB,GK,OVA
0,219461,E. Palmer-Brown,23,United States,FK Austria Wien,CB,CB,"FK Austria Wien Jun 30, 2021 On Loan","6'2""",194lbs,...,61+2,61+2,59+2,61+2,67+2,67+2,67+2,61+2,16+2,67
1,221896,D. Avdijaj,22,Kosovo,Heart of Midlothian,CAM,LM CAM,Heart of Midlothian 2020 ~ 2020,"5'8""",154lbs,...,47+2,47+2,49+2,45+2,38+2,38+2,38+2,45+2,17+2,68
2,247428,D. Ochoa,19,United States,Real Salt Lake,GK,GK,Real Salt Lake 2018 ~ 2020,"6'2""",176lbs,...,18+2,18+2,16+2,16+2,18+2,18+2,18+2,16+2,53+2,54
3,255120,N. Kenneh,16,England,Leeds United,CDM,CB CDM RB,Leeds United 2020 ~ 2022,"6'3""",170lbs,...,54+2,54+2,53+2,53+2,54+2,54+2,54+2,53+2,11+2,55
4,215556,E. Fernandes,24,Switzerland,1. FSV Mainz 05,CDM,CM CDM,1. FSV Mainz 05 2019 ~ 2023,"6'2""",170lbs,...,72+2,72+2,70+2,69+2,68+2,68+2,68+2,69+2,18+2,70

In [9]:
def clean_data(df):

# Standardize our columns so they look the same
    df.columns =[colname.lower().replace(' ','_') for colname in df.columns]

# Drop values we not need

    df=df.drop(columns=['id', 'team_&_contract','joined', 'loan_date_end', 'position','contract','ls', 'st', 'rs', 'lw', 'lf', 'cf', 'rf', 'rw', 'lam', 'cam', 'ram',
       'lm', 'lcm', 'cm', 'rcm', 'rm', 'lwb', 'ldm', 'cdm', 'rdm', 'rwb', 'lb',
       'lcb', 'cb', 'rcb', 'rb', 'gk','release_clause','attacking', 'crossing',
       'finishing', 'heading_accuracy', 'short_passing', 'volleys', 'skill',
        'dribbling', 'curve', 'fk_accuracy', 'long_passing', 'ball_control',
       'movement', 'acceleration', 'sprint_speed', 'agility', 'reactions',
       'balance', 'power', 'shot_power', 'jumping', 'stamina', 'strength',
       'long_shots', 'mentality', 'aggression', 'interceptions', 'positioning',
       'vision', 'penalties', 'composure', 'defending', 'marking',
       'standing_tackle', 'sliding_tackle', 'goalkeeping', 'gk_diving',
       'gk_handling', 'gk_kicking', 'gk_positioning', 'gk_reflexes', 'value', 'base_stats','height', 'weight','w/f','name', 'nationality', 'club'], axis = 1)

#Convert wage into integers
    df['wage'] = [x.replace('€', '').replace('K','000') for x in df['wage']]
    df['wage'] = df['wage'].apply(pd.to_numeric)
# Get rid of the star
    
    df['sm'] = [i.replace('★','') for i in df['sm']]
    df['sm'] = df['sm'].apply(pd.to_numeric)
    
    df['ir'] = [i.replace('★','') for i in df['ir']]
    df['ir'] = df['ir'].apply(pd.to_numeric)

# Get rid of the NaN values
    df = df.dropna()
    
# Change hits into integer
    
    return df

In [10]:
fifa_predict = clean_data(fifa_predict)

In [11]:
fifa_predict.head()

,age,bp,foot,growth,wage,total_stats,sm,a/w,d/w,ir,pac,sho,pas,dri,def,phy,hits,ova
0,23,CB,Right,7,5000,1551,2,Low,High,1,64,30,50,50,66,74,34,67
1,22,CAM,Right,5,3000,1726,3,High,Low,1,74,67,62,74,24,57,12,68
2,19,GK,Right,17,500,808,1,Medium,Medium,1,56,52,53,55,26,53,3,54
3,16,CDM,Right,23,500,1381,2,Medium,Medium,1,58,34,47,52,53,59,6,55
4,24,CDM,Right,5,13000,1864,2,Medium,Medium,1,67,62,68,70,69,71,45,70

In [12]:
fifa_predict.dtypes

age             int64
bp             object
foot           object
growth          int64
wage            int64
total_stats     int64
sm              int64
a/w            object
d/w            object
ir              int64
pac             int64
sho             int64
pas             int64
dri             int64
def             int64
phy             int64
hits           object
ova             int64
dtype: object